# Generated by Django 4.1.7 on 2023-03-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("prediction", models.CharField(blank=True, max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
